# Generated by Django 4.2.7 on 2023-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('place_name', 'city'), name='unique_place_name_city'),
        ),
    ]
