# Generated by Django 4.2.7 on 2023-12-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_city_alter_place_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
