# Generated by Django 4.2.7 on 2023-12-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_zlhcpb', upload_to='positive/profile_pictures/'),
        ),
    ]
