# Generated by Django 4.2.7 on 2023-12-06 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_place'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0002_rename_user_likes_owner_alter_likes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='posts.post'),
        ),
    ]
